network:
    timeout: 30s
    retries: 3
    dns_servers:
        - 8.8.8.8
        - 1.1.1.1
tls:
    minversion: 771
    maxversion: 772
    ciphersuites: []
    servername: ""
    nextprotos: []
concurrency:
    max_concurrent: 8
    check_timeout: 30s
    cache_ttl: 5m0s
output:
    color: true
    verbose: false
    format: table
cache:
    dns_enabled: true
    result_enabled: true
    ttl: 5m0s
    max_size: 1000
batch:
    stream_output: false
    progress_bar: true
    report_format: text
    timeout: 1m0s
